added log_level option; using debug log level by default
insales/paperclip pull request #96
Opened 2024-05-02 18:16 UTC by adrianopol

2024-05-02 18:20 UTC, ngoral commented on lib/paperclip.rb
> +      ActiveRecord::Base.logger.send(options[:log_level], "[paperclip] #{message}") if options[:log]
Так, а если мы захотим другой логгер?

2024-05-02 18:23 UTC, adrianopol commented on lib/paperclip.rb
> +      ActiveRecord::Base.logger.send(options[:log_level], "[paperclip] #{message}") if options[:log]
так он и сейчас гвоздями прибит

2024-05-02 18:24 UTC, adrianopol commented on lib/paperclip.rb
> +      ActiveRecord::Base.logger.send(options[:log_level], "[paperclip] #{message}") if options[:log]
и для моков оно тоже не используется:
```
test/test_helper.rb
54:ActiveRecord::Base.logger = Logger.new(File.dirname(__FILE__) + "/debug.log")
```

2024-05-03 09:16 UTC, Vasfed commented on lib/paperclip.rb
> +      ActiveRecord::Base.logger.send(options[:log_level], "[paperclip] #{message}") if options[:log]
Лучше гвозди из логгера повытащить

2024-05-03 09:30 UTC, ngoral commented on lib/paperclip.rb
> +      ActiveRecord::Base.logger.send(options[:log_level], "[paperclip] #{message}") if options[:log]
Ну это всё ещё не повод заивать последний гвоздь в него..) (Да, согласна с Васей, что гвозди лучше вытаскивать, чем забивать в данной конкретной ситуации)
Давай вернём =)

2024-05-03 11:48 UTC, adrianopol commented on lib/paperclip.rb
> +      ActiveRecord::Base.logger.send(options[:log_level], "[paperclip] #{message}") if options[:log]
@ngoral , @Vasfed , обновил

2024-05-13 13:58 UTC, Vasfed requested changes
@adrianopol если еще полон решимости это вмержить - надо починить тесты, проще это сделать если сумеешь запустить их локально

2024-06-20 06:00 UTC, closed without merging